# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]

# TODO replace acceleration limits with correct values

joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 5.027
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_2:
    has_velocity_limits: true
    max_velocity: 4.189
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_3:
    has_velocity_limits: true
    max_velocity: 5.236
    has_acceleration_limits: true
    max_acceleration: 0.87266
  joint_4:
    has_velocity_limits: true
    max_velocity: 6.981
    has_acceleration_limits: true
    max_acceleration: 1.11701
  joint_5:
    has_velocity_limits: true
    max_velocity: 7.069
    has_acceleration_limits: true
    max_acceleration: 1.11701
  joint_6:
    has_velocity_limits: true
    max_velocity: 10.472
    has_acceleration_limits: true
    max_acceleration: 1.46608
